### ISSUE TITLE
The pretrained model file may be broken.

### ISSUE THREAD

**Issue by vujadeyoon** [Xt-Chen/SARPN#1]
Hello, Xt-Chen.
I really thank you for releasing the SARPN codes for monocular depth estimation.

Unfortunately, the pretrained model that is uploaded on the MS OneDrive may be broken.
when trying to decompress the tar file, the file can't be decompressed.

Please check it one more time.
Thanks.

**Comment by Xt-Chen** [comment]
Hello，vujadeyoon.
The pre-training model has not been broken. Our pre-training model is saved in .tar; However, you don't need to untar it. Please use torch.load() to load it. You can find the specific implementation in the "load parameters" process in train.py.
