### ISSUE TITLE
About the depth ground truth pre-processing?

### ISSUE THREAD

**Issue by alanlyawen** [Xt-Chen/SARPN#10]
Thank for your great work! 
I am a little confused about the dataloader code! Why divide the depth groundtruth by 255 and multiply it by 10 in training and divide it by 1000 in evaluate? Will this affect the evaluation results? If i need adjust it?

**Comment by Xt-Chen** [comment]
Because the depth scale of training data and test data are different, these operations are done in order to ensure the consistency of training and testing.

**Comment by alanlyawen** [comment]
> Because the depth scale of training data and test data are different, these operations are done in order to ensure the consistency of training and testing.

Thanks for your timely reply!
