### ISSUE TITLE
distance measurement

### ISSUE THREAD

**Issue by xueyingtianhua** [Xt-Chen/SARPN#3]
Is there any possible to estimate distance?

**Comment by Xt-Chen** [comment]
Yes, if you want to apply this method to your own problem, you need to retrain or finetune our network with your own data. Otherwise, domain shift may occur due to different data distributions.

**Comment by Aymdr** [comment]
Hello，I'm interested how to get a specific distance value from the depth map.

**Comment by Xt-Chen** [comment]
Hello, the value of each pixel in the depth map represents the vertical distance from a point in the scene to the center of the camera.

**Comment by Aymdr** [comment]
Sorry, how to get the correspondence between pixel value and distance?

**Comment by Xt-Chen** [comment]
The depth map output by the network corresponds to pre-processed ground truth used during training. If you want to obtain the absolute depth, the reverse pre-processing is needed.
