### ISSUE TITLE
parameter definition

### ISSUE THREAD

**Issue by zxnnnn** [Xt-Chen/SARPN#5]
I want to know what is the definition of adff_num_features, and how is 1280 calculated?

**Comment by Xt-Chen** [comment]
There are a total of five scale feature maps. The number of channels for each scale feature map is 256, concatenating them to form a feature map with 1280 channels.

**Comment by zxnnnn** [comment]
Thank you for your reply！

I think I know.That's to say: The number of MFF output channels for scale5 is 1280,The number of MFF output channels for scale4 is 640，Similarly, scale3 is 320, scale2 is 160, scale1 is 80.




------------------ 原始邮件 ------------------
发件人: "Xt-Chen"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 下午2:36
收件人: "Xt-Chen/SARPN"<SARPN@noreply.github.com>;
抄送: "1749194098"<1749194098@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Xt-Chen/SARPN] parameter definition (#5)




There are a total of five scale feature maps. The number of channels for each scale feature map is 256, concatenating them to form a feature map with 1280 channels.

**Comment by zxnnnn** [comment]
> There are a total of five scale feature maps. The number of channels for each scale feature map is 256, concatenating them to form a feature map with 1280 channels.
