### ISSUE TITLE
Something wrong in train.py

### ISSUE THREAD

**Issue by Xiangjun-Gao** [Xt-Chen/SARPN#7]
In line 48 of train.py, your code shows`  loadckpt = os.path.join(args.logdir, all_saved_ckpts[-1])`
Maybe `loadckpt = os.path.join(args.checkpoint_dir, all_saved_ckpts[-1])` is right. I am not sure.

**Comment by Xt-Chen** [comment]
Thank you, I have corrected this error in the latest version.
