### ISSUE TITLE
train loss less than zero

### ISSUE THREAD

**Issue by visonpon** [Xt-Chen/SARPN#8]
Hi @Xt-Chen ,
Thanks for your excellent work, but when I train your model on my own datasets, the losses are less than zero, could you give me some advice?

**Comment by Xt-Chen** [comment]
That's reasonable, you can see the definition of loss. Its minimum value is not 0.

**Comment by VladimirYugay** [comment]
Hey there, 

I've checked the loss definition [here](https://arxiv.org/pdf/1803.08673.pdf), but it's still a little bit unclear, what's the minimal value of the loss?
