### ISSUE TITLE
About Reproducible results

### ISSUE THREAD

**Issue by cvgogogo** [Xt-Chen/SARPN#9]
Hi Xt-Chen,

Thanks for your nice work. I find it interesting, so I cloned the code and re-trained on my PC without any changes except the dataset path. However, I tried several times, the results varies a lot. Take the ABS metric as an example, the results were 0.2%-0.4% worse than the reported results in your paper. I checked the code and could not find any operations to fix the rand seeds. I thought this might be the main potential issue that I could not reproduce the result. 
As above, Would you please help me to cross the problem and I wonder if you tried many times and chosen the best one? or you just trained one time?

Thanks again.

Cheers, 
cvgogogo

**Comment by Xt-Chen** [comment]
Hi,
Since the parameters in the adff and rpd modules in the network are initialized randomly, the results of each training may be slightly different. During the training process, I also used the early stopping to avoid overfitting.
Hope it helps you

**Comment by cvgogogo** [comment]
> 
> 
> Hi,
> Since the parameters in the adff and rpd modules in the network are initialized randomly, the results of each training may be slightly different. During the training process, I also used the early stopping to avoid overfitting.
> Hope it helps you
Thank you for your reply.
